name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint (flake8)
      run: |
        pip install flake8
        flake8 || true

    - name: Check openai compatibility
      run: |
        python - <<'PY'
import pkgutil
import sys
if not pkgutil.find_loader('openai'):
    print('openai package not installed')
    sys.exit(1)
import openai
v = getattr(openai, '__version__', '0')
major = int(v.split('.')[0]) if v and v[0].isdigit() else 0
if major < 1:
    print(f'Installed openai version {v} is unsupported; require >=1.0.0')
    sys.exit(1)
print(f'openai version {v} OK')
PY

    - name: Run tests
      run: |
        pytest -q
